# Site settings
title: Jadon Hansell
description: Jadon Hansell\'s Personal Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jadon Hansell
user_description: This is my description
user_title: Software Developer
email: JadonHansell@gmail.com
twitter_username: Alcamore
github_username:  Alcamore
gplus_username:  null

# Google-analytics
google-analytics:
  id: "G-CJ9CC00N91"

exclude: ['package.json', 'src' , 'node_modules']
